### ISSUE TITLE
EZ2 Gerbers

### ISSUE THREAD

**Issue by sbcat** [ika-musume/ArcadeStuffs#1]
Hi, would you be able to add the Gerber files and BOM for the EZ2 I/O board to the repository? (or you could send them to me if you prefer keeping them private) I'm in the middle of DIYing a setup for the game, and the original boards are really hard to find, so I wanted to try fabricating your design. Not sure if any have ever actually been made, but if you know of any considerations I should be aware of when it comes to getting these fabbed I would appreciate it. Thank you!

**Comment by ika-musume** [comment]
Hi. Unfortunately, it was a paid project by my friend, and all resources except the schematic are not publicly available. What I had to do was design a repro and deliver the finished products to him. I don't have any further permissions.

I've verified that there are no errors in that schematic. If you want to make your own board, you will also need the firmware file for the AT89C51 MCU.
